services:
  # database:
  #   image: postgres:15-alpine
  #   container_name: database
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USERNAME}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_DB=${DATABASE_NAME}
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # target: ${ENV}
    container_name: backend
    ports:
      - '${PORT_BACKEND}:3001'
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      - NODE_ENV=${ENV}
      - PORT=${PORT_BACKEND}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASS=${EMAIL_PASS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus
    ports:
      - "${PORT_PROMETHEUS}:9090"
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "${PORT_GRAFANA}:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # target: ${ENV}
    container_name: frontend
    ports:
      - '${PORT_FRONTEND}:3000'
    environment:
      - NODE_ENV=${ENV}
      - PORT=${PORT_FRONTEND}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  grafana-storage:

networks:
  app-network:
    driver: bridge
